### ISSUE TITLE
如何报名呢？

### ISSUE THREAD

**Issue by xuyue101012** [huji0624/progame#5]
有建一个群吗？在哪里报名呢？今天 游戏排行榜页面报错，无法获取到数据了。

**Comment by jurieo** [comment]
公司大群聊天记录里有个二维码，可以扫码进群。

**Comment by jurieo** [comment]
> 有建一个群吗？在哪里报名呢？今天 游戏排行榜页面报错，无法获取到数据了。

公司大群聊天记录里有个二维码，可以扫码进群。

**Comment by xuyue101012** [comment]
好的，知道了

**Comment by xuyue101012** [comment]
好的 知道了 谢谢
